name: CI

on: [push] # always will be pushed

jobs: 
  sast_scan: # security sast scanning tool
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v2

    - name: Set up Python #install tools what we need
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json # everything is scanned and output report implemented

    - name: Upload Artifact # upload the report as an artifact that it is still available after job is executed
      uses: actions/upload-artifact@v4
      if: always() # even the previous steps fails, this is executed
      with:
        name: bandit-findings
        path: bandit-report.json

  image_scan: 
    name: Build image and Run Image Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Docker # set up docker
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub # login to docker using global variables to avoid hard coding user credentials
      run: echo "${{ secrets.SECURE_PASSWORD }}" | docker login -u "${{ secrets.SECURE_USER }}" --password-stdin

    - name: Build Docker Image # image need to be built before scanning it
      run: docker build -f Dockerfile -t vulnerableapp:latest .

    - name: Run Docker Scout Scan # run the docker scan: summary of the image and list detailed security vulnerabilities
      run: |
        docker scout quickview vulnerableapp:latest --only-severities critical,high > docker-scout-report.txt
        docker scout cves vulnerableapp:latest --only-severities critical,high >> docker-scout-report.txt

    - name: Upload Docker Scout Artifact # upload the Docker Scout report as an artifact
      uses: actions/upload-artifact@v4
      if: always()  # even if previous steps fail, this is executed
      with:
        name: docker-scout-findings
        path: docker-scout-report.json
  
      
      
