name: CI

on: [push] # always will be pushed

jobs: 
  sast_scan: # security sast scanning tool
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v2

    - name: Set up Python #install tools what we need
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r . -f json bandit-report.json # everything is scanned and output report implemented

    - name: Upload Artifact # upload the report as an artifact that it is still available after job is executed
      uses: actions/upload-artifact@v3
      if: always # even the previous steps fails, this is executed
      with:
        name: bandit-findings
        path: bandit-report.json
      
      
      
      
